
---
- hosts: fortidcrsd
  connection: httpapi
  gather_facts: false
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443

  tasks:
    - name: Configure global attributes.
      fortios_system_global:
        vdom:  "{{ vdom }}"
        access_token: "{{ fortios_access_token }}" #if you prefer access token based authentication, add this line.
        system_global:
          admintimeout: "60"

#   - name: Get firwall system status as a test
#     fortios_configuration_fact:
#       vdom: "{{ vdom }}"
#       access_token: "88H3gq1gdg8Gy7dQ33t3xjNq8kc4d6"
#       selector: system_status
#     register: _system_status
