- hosts: fortidcrsd
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: false
  
  vars:
    vdom: "1-DC"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443
   
    vlanid: "580"
    vlanname: "VL580"
    vlanalias: "580-GT-CLIENTS"
    vlannetwork: "10.205.164"
    zonename: "GT-VDI"

  tasks:
  - name: Configure zones to group two or more interfaces.
    fortios_system_zone:
      vdom:  "{{ vdom }}"
      state: present
      access_token: "{{ fortios_access_token }}"
      system_zone:
        interface:
         -
            interface_name: "{{ vlanname }}"
        intrazone: "allow"
        name: "{{ zonename }}"

