---

- hosts: nexus
  become: no
  gather_facts: false
  vars_prompt:

    - name: vlanid
      prompt: Welk Vlan wil je verhuizen naar de DC-Firewalls?
      private: false

    - name: vlannaam
      prompt: Wat is de naam voor dit Vlan?
      private: false

  tasks:

    - name: Disable Vlan
      cisco.nxos.nxos_interfaces:
        config:
        - name: "vlan{{ vlanid }}"
          enabled: false
        state: merged

